services:
  - type: web
    name: onefocus-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      # Serve real files first (JS/CSS/images)
      - type: rewrite
        source: /assets/*
        destination: /assets/:splat
      - type: rewrite
        source: /favicon.*
        destination: /favicon.ico

      # SPA fallback: rewrite all other paths to index.html
      - type: rewrite
        source: /*
        destination: /index.html

    # Optional: define environment variables for Vite at build time
    # envVars:
    #   - key: VITE_SERVER_URL
    #     value: https://your-backend.onrender.com