services:
  - type: web
    name: onefocus-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      # Canonical redirect for index.html
      - type: redirect
        source: /index.html
        destination: /
        statusCode: 301

      # SPA fallback: let the client router handle deep links
      - type: rewrite
        source: /*
        destination: /index.html

    # Optional: define environment variables for Vite at build time
    # envVars:
    #   - key: VITE_SERVER_URL
    #     value: https://your-backend.onrender.com